### PR TITLE
Rebase on top of birch release

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by Kelketek** [comment]
@e-kolpakov The tests are green, and the additional commits for List/Dict import look fine to me, though I need to test them manually over in the other PR. Once that gets the thumbs up, this has a thumbs up from me, too.

**Comment by antoviaque** [comment]
@e-kolpakov Why do you need to import these additional commits?

* Allowed List and Dict field to coerce values from JSON or literals. Kelketek authored on Nov 20, 2014
* Added tests for JSON/lit coersion. Kelketek authored on Jan 13
* Fixed broken tests 

The first commit seem to be from https://github.com/edx/XBlock/pull/274/commits right? Wasn't this closed in favor of https://github.com/edx/XBlock/pull/244 , which lead to get https://github.com/edx-solutions/XBlock/commit/7802e12083c2230274fe46b1ac4cad1dafb832b7 merged upstream instead, and which is already present in this PR.

**Comment by e-kolpakov** [comment]
@antoviaque first two - because they are on edx-solutions/XBlock/master. Last one is fresh - `fields_to_init` was renamed to `FIELDS_TO_INIT` upstream, so some tests were fixed, but not the ones added in previous two commits. If we're to remove them that fix won't be needed as well.

I might get purpose of edx-solutions/XBlock/master wrong - for some reason I thought it might be used for edx-solutions/edx-platform instances. If they aren't - it should be safe to remove those commits, but if they actually do - there might be some issues with that.

**Comment by antoviaque** [comment]
@e-kolpakov These two commits were merged to edx-solutions/edx-platform while https://github.com/edx/XBlock/pull/274 was making its way upstream. Now that the result of that PR got merged in https://github.com/edx/XBlock/pull/244 and is in the commits we are getting from upstream, we need to remove the previous implementation, to keep only the solution accepted by upstream. If that creates issues, we need to figure out what - if the fix we got merged upstream ourselves doesn't cover our needs, we missed something somewhere : )

**Comment by bradenmacdonald** [comment]
@e-kolpakov Can you not remove those three commits and just keep the "Fixed exporting List and Dict with unicode contents + tests" commit that you made most recently?

**Comment by e-kolpakov** [comment]
@bradenmacdonald Sure I can :) Moreover, that last commit is likely to be useless if I remove the previous two.

**Comment by bradenmacdonald** [comment]
:+1:

**Comment by bradenmacdonald** [comment]
@e-kolpakov Would it be possible to include 0b865f62f2deaa81b77f819b9b7df0303cb0f70c as well? At least one course doesn't upgrade properly from mentoring v1 to problem builder because of XML comments, and that's the fix.

**Comment by e-kolpakov** [comment]
@bradenmacdonald done, but please note every time I add one commit I have to do at least smoke testing of nine blocks - please try to do bulk updates at least :)

**Comment by bradenmacdonald** [comment]
@e-kolpakov Ya, sorry about that. And thanks :)

**Pull request merged**
